hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
  command:
    default:
      execution:
        timeout.enabled: true
        isolation.thread.timeoutInMilliseconds: 10815000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker:
        enabled: false
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
    downloadCommandKey:
      execution.isolation.semaphore.maxConcurrentRequests: 2
      execution.isolation.thread.timeoutInMilliseconds: 20000
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: 20
      maximumSize: 200
#    waitingService:
#      allowMaximumSizeToDivergeFromCoreSize: true
##      coreSize: 2
##      maximumSize: 1
#      maxQueueSize: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    com.example.hystrixthreadcount: debug
