hystrix:
  command:
    default:
      execution:
        timeout.enabled: true
        isolation.thread.timeoutInMilliseconds: 10000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker:
        enabled: true
#        requestVolumeThreshold: 5
#        errorThresholdPercentage: 50
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: 1
      maximumSize: 2
