hystrix:
  command:
    default:
      execution:
        timeout.enabled: true
        isolation.thread.timeoutInMilliseconds: 10815000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker:
        enabled: false
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50

    userService:
      execution.isolation.semaphore.maxConcurrentRequests: 1
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: 20
      maximumSize: 200
